rm(list = ls())
library(readr)
library('data.table')
library(cathayR)
library(dplyr)
inicathayR()
setwd("~/R/ML/CAR")

########################################################################################
# 欄位轉換函數
typechange = function(dataset,numeric_col,integer_col,factor_col,Date_col,character_col){
  dataset = as.data.frame(dataset)
  if(sum(numeric_col!="")>0) dataset[numeric_col] = lapply(dataset[numeric_col], as.numeric) 
  if(sum(integer_col!="")>0) dataset[integer_col] = lapply(dataset[integer_col], as.integer) 
  if(sum(factor_col!="")>0) dataset[factor_col] = lapply(dataset[factor_col], as.factor) 
  if(sum(Date_col!="")>0) dataset[Date_col] = lapply(dataset[Date_col], as.Date) 
  if(sum(character_col!="")>0) dataset[character_col] = lapply(dataset[character_col], as.character) 
  return(dataset)
}

# 智能探勘函數
autoDataMining = function(dataset){
  DM_result = data.frame()
  for (col_name in names(dataset)){
    VARIABLE_NAME = col_name # 變數名稱
    R_DATATYPE = class(dataset[[col_name]]) # R資料型態
    NUMBER_OF_MISSING_VALUES = sum(is.na(dataset[[col_name]])) # 缺失值總數
    PERCENTAGE_OF_MISSING_VALUES = round(NUMBER_OF_MISSING_VALUES/nrow(dataset),4)*100 # 缺失值占比
    if(NUMBER_OF_MISSING_VALUES>0){ # 元素個數
      NUMBER_OF_LEVELS_WITHOUT_NULL = length(unique(dataset[[col_name]]))-1
    }else{
      NUMBER_OF_LEVELS_WITHOUT_NULL = length(unique(dataset[[col_name]]))
    }
    if(R_DATATYPE %in% c('character','factor','Date')){
      MINIMUM_NUMERIC_VALUES = NA
      MAXIMUM_NUMERIC_VALUES = NA
      MEAN = NA
      STARDARD_DEVIATIO = NA
    }else{
      MINIMUM_NUMERIC_VALUES = min(dataset[[col_name]], na.rm = T) # 極小值
      MAXIMUM_NUMERIC_VALUES = max(dataset[[col_name]], na.rm = T) # 極大值
      MEAN = mean(dataset[[col_name]], na.rm = T)
      STARDARD_DEVIATIO = sd(dataset[[col_name]], na.rm = T)
    }
    DM_result_tmp = data.frame(VARIABLE_NAME=VARIABLE_NAME,R_DATATYPE=R_DATATYPE,NUMBER_OF_MISSING_VALUES=NUMBER_OF_MISSING_VALUES,PERCENTAGE_OF_MISSING_VALUES=PERCENTAGE_OF_MISSING_VALUES,NUMBER_OF_LEVELS_WITHOUT_NULL=NUMBER_OF_LEVELS_WITHOUT_NULL,MINIMUM_NUMERIC_VALUES=MINIMUM_NUMERIC_VALUES,MAXIMUM_NUMERIC_VALUES=MAXIMUM_NUMERIC_VALUES,MEAN=MEAN,STARDARD_DEVIATIO=STARDARD_DEVIATIO)
    DM_result = rbind (DM_result,DM_result_tmp)
  }
  return(DM_result)
}

# 模型表現函數
report_metrics = function(method,y_ture,y_pred,y_score){
  ans = data.frame(Algorithm = method,
                   ROC_AUC = AUC(y_pred, y_ture),
                   Accuracy = Accuracy(y_pred, y_ture),
                   Precision = Precision(y_ture, y_pred, positive = '1'),
                   Recall = Recall(y_ture, y_pred, positive = '1'),
                   F1_Score = F1_Score(y_ture, y_pred, positive  = '1')
  )
  return(ans)
}
########################################################################################



# 讀取資料
dataset = read_csv('~/R/ML/CAR/dataset/CAR_ABT_GROUP2.csv')
dim(dataset) # 534361*320
class(dataset)
glimpse(dataset)

# 定義各欄位資料型態
numeric_col = c('DISCOUNT_PREMIUM_AGN',	'CONCLUDE_NTD_AMOUNT_AGN',	'POLICY_COUNT_AGN',	'LOSS_RATE_AGN',	'INSRNCE_AMOUNT',  'DEPRECIA_RATE',	'LOSS_RATE')
integer_col1 = c('DISCOUNT_PREMIUM', 'INS_ISSUE_YEAR', 'CAR_AGE', 'INS_AGE', 'APC_AGE', 'ONE_INSUR_AMOUNT', 'ONE_INSUR_CNT', 'TWO_INSUR_AMOUNT', 'TWO_INSUR_CNT', 'THREE_INSUR_AMOUNT', 'THREE_INSUR_CNT', 'FOUR_INSUR_AMOUNT', 'FOUR_INSUR_CNT', 'FIVE_INSUR_AMOUNT', 'FIVE_INSUR_CNT', 'ONE_PARK_CNT', 'TWO_PARK_CNT', 'THREE_PARK_CNT', 'BUMP_CNT', 'ONE_INSUR_AMOUNT_BODY', 'ONE_INSUR_CNT_BODY', 'TWO_INSUR_AMOUNT_BODY', 'TWO_INSUR_CNT_BODY', 'THREE_INSUR_AMOUNT_BODY', 'THREE_INSUR_CNT_BODY', 'FOUR_INSUR_AMOUNT_BODY', 'FOUR_INSUR_CNT_BODY', 'FIVE_INSUR_AMOUNT_BODY', 'FIVE_INSUR_CNT_BODY', 'ONE_PARK_CNT_BODY', 'TWO_PARK_CNT_BODY', 'THREE_PARK_CNT_BODY', 'BUMP_CNT_BODY', 'ONE_INSUR_AMOUNT_BURG', 'ONE_INSUR_CNT_BURG', 'TWO_INSUR_AMOUNT_BURG', 'TWO_INSUR_CNT_BURG', 'THREE_INSUR_AMOUNT_BURG', 'THREE_INSUR_CNT_BURG', 'FOUR_INSUR_AMOUNT_BURG', 'FOUR_INSUR_CNT_BURG', 'FIVE_INSUR_AMOUNT_BURG', 'FIVE_INSUR_CNT_BURG', 'ONE_PARK_CNT_BURG', 'TWO_PARK_CNT_BURG', 'THREE_PARK_CNT_BURG', 'BUMP_CNT_BURG', 'ONE_INSUR_AMOUNT_THIRD', 'ONE_INSUR_CNT_THIRD', 'TWO_INSUR_AMOUNT_THIRD', 'TWO_INSUR_CNT_THIRD', 'THREE_INSUR_AMOUNT_THIRD', 'THREE_INSUR_CNT_THIRD', 'FOUR_INSUR_AMOUNT_THIRD', 'FOUR_INSUR_CNT_THIRD', 'FIVE_INSUR_AMOUNT_THIRD', 'FIVE_INSUR_CNT_THIRD', 'ONE_PARK_CNT_THIRD', 'TWO_PARK_CNT_THIRD', 'THREE_PARK_CNT_THIRD', 'BUMP_CNT_THIRD', 'ONE_INSUR_AMOUNT_CUST', 'ONE_INSUR_CNT_CUST', 'TWO_INSUR_AMOUNT_CUST', 'TWO_INSUR_CNT_CUST', 'THREE_INSUR_AMOUNT_CUST', 'THREE_INSUR_CNT_CUST', 'FOUR_INSUR_AMOUNT_CUST', 'FOUR_INSUR_CNT_CUST', 'FIVE_INSUR_AMOUNT_CUST', 'FIVE_INSUR_CNT_CUST', 'ONE_PARK_CNT_CUST', 'TWO_PARK_CNT_CUST', 'THREE_PARK_CNT_CUST', 'BUMP_CNT_CUST', 'ONE_INSUR_AMOUNT_FORCE', 'ONE_INSUR_CNT_FORCE', 'TWO_INSUR_AMOUNT_FORCE', 'TWO_INSUR_CNT_FORCE', 'THREE_INSUR_AMOUNT_FORCE', 'THREE_INSUR_CNT_FORCE', 'FOUR_INSUR_AMOUNT_FORCE', 'FOUR_INSUR_CNT_FORCE', 'FIVE_INSUR_AMOUNT_FORCE', 'FIVE_INSUR_CNT_FORCE', 'ONE_PARK_CNT_FORCE', 'TWO_PARK_CNT_FORCE', 'THREE_PARK_CNT_FORCE', 'BUMP_CNT_FORCE', 'ONE_INSUR_AMOUNT_OTHER', 'ONE_INSUR_CNT_OTHER', 'TWO_INSUR_AMOUNT_OTHER', 'TWO_INSUR_CNT_OTHER', 'THREE_INSUR_AMOUNT_OTHER', 'THREE_INSUR_CNT_OTHER', 'FOUR_INSUR_AMOUNT_OTHER', 'FOUR_INSUR_CNT_OTHER', 'FIVE_INSUR_AMOUNT_OTHER', 'FIVE_INSUR_CNT_OTHER', 'ONE_PARK_CNT_OTHER', 'TWO_PARK_CNT_OTHER', 'THREE_PARK_CNT_OTHER', 'BUMP_CNT_OTHER', 'ONE_INSUR_AMOUNT_COM', 'ONE_INSUR_CNT_COM', 'TWO_INSUR_AMOUNT_COM', 'TWO_INSUR_CNT_COM', 'THREE_INSUR_AMOUNT_COM', 'THREE_INSUR_CNT_COM', 'FOUR_INSUR_AMOUNT_COM', 'FOUR_INSUR_CNT_COM', 'FIVE_INSUR_AMOUNT_COM', 'FIVE_INSUR_CNT_COM', 'ONE_PARK_CNT_COM', 'TWO_PARK_CNT_COM', 'THREE_PARK_CNT_COM', 'BUMP_CNT_COM', 'ONE_INSUR_AMOUNT_C', 'ONE_INSUR_CNT_C', 'TWO_INSUR_AMOUNT_C', 'TWO_INSUR_CNT_C', 'THREE_INSUR_AMOUNT_C', 'THREE_INSUR_CNT_C', 'FOUR_INSUR_AMOUNT_C', 'FOUR_INSUR_CNT_C', 'FIVE_INSUR_AMOUNT_C', 'FIVE_INSUR_CNT_C', 'ONE_PARK_CNT_C', 'TWO_PARK_CNT_C', 'THREE_PARK_CNT_C', 'IS_BUMP_C', 'BUMP_CNT_C', 'ONE_INSUR_AMOUNT_BODY_C', 'ONE_INSUR_CNT_BODY_C', 'TWO_INSUR_AMOUNT_BODY_C', 'TWO_INSUR_CNT_BODY_C', 'THREE_INSUR_AMOUNT_BODY_C', 'THREE_INSUR_CNT_BODY_C', 'FOUR_INSUR_AMOUNT_BODY_C', 'FOUR_INSUR_CNT_BODY_C', 'FIVE_INSUR_AMOUNT_BODY_C', 'FIVE_INSUR_CNT_BODY_C', 'ONE_PARK_CNT_BODY_C', 'TWO_PARK_CNT_BODY_C', 'THREE_PARK_CNT_BODY_C', 'BUMP_CNT_BODY_C', 'ONE_INSUR_AMOUNT_BURG_C', 'ONE_INSUR_CNT_BURG_C', 'TWO_INSUR_AMOUNT_BURG_C', 'TWO_INSUR_CNT_BURG_C', 'THREE_INSUR_AMOUNT_BURG_C', 'THREE_INSUR_CNT_BURG_C', 'FOUR_INSUR_AMOUNT_BURG_C', 'FOUR_INSUR_CNT_BURG_C', 'FIVE_INSUR_AMOUNT_BURG_C')
integer_col2 = c('FIVE_INSUR_CNT_BURG_C', 'ONE_PARK_CNT_BURG_C', 'TWO_PARK_CNT_BURG_C', 'THREE_PARK_CNT_BURG_C', 'BUMP_CNT_BURG_C', 'ONE_INSUR_AMOUNT_THIRD_C', 'ONE_INSUR_CNT_THIRD_C', 'TWO_INSUR_AMOUNT_THIRD_C', 'TWO_INSUR_CNT_THIRD_C', 'THREE_INSUR_AMOUNT_THIRD_C', 'THREE_INSUR_CNT_THIRD_C', 'FOUR_INSUR_AMOUNT_THIRD_C', 'FOUR_INSUR_CNT_THIRD_C', 'FIVE_INSUR_AMOUNT_THIRD_C', 'FIVE_INSUR_CNT_THIRD_C', 'ONE_PARK_CNT_THIRD_C', 'TWO_PARK_CNT_THIRD_C', 'THREE_PARK_CNT_THIRD_C', 'BUMP_CNT_THIRD_C', 'ONE_INSUR_AMOUNT_CUST_C', 'ONE_INSUR_CNT_CUST_C', 'TWO_INSUR_AMOUNT_CUST_C', 'TWO_INSUR_CNT_CUST_C', 'THREE_INSUR_AMOUNT_CUST_C', 'THREE_INSUR_CNT_CUST_C', 'FOUR_INSUR_AMOUNT_CUST_C', 'FOUR_INSUR_CNT_CUST_C', 'FIVE_INSUR_AMOUNT_CUST_C', 'FIVE_INSUR_CNT_CUST_C', 'ONE_PARK_CNT_CUST_C', 'TWO_PARK_CNT_CUST_C', 'THREE_PARK_CNT_CUST_C', 'BUMP_CNT_CUST_C', 'ONE_INSUR_AMOUNT_FORCE_C', 'ONE_INSUR_CNT_FORCE_C', 'TWO_INSUR_AMOUNT_FORCE_C', 'TWO_INSUR_CNT_FORCE_C', 'THREE_INSUR_AMOUNT_FORCE_C', 'THREE_INSUR_CNT_FORCE_C', 'FOUR_INSUR_AMOUNT_FORCE_C', 'FOUR_INSUR_CNT_FORCE_C', 'FIVE_INSUR_AMOUNT_FORCE_C', 'FIVE_INSUR_CNT_FORCE_C', 'ONE_PARK_CNT_FORCE_C', 'TWO_PARK_CNT_FORCE_C', 'THREE_PARK_CNT_FORCE_C', 'BUMP_CNT_FORCE_C', 'ONE_INSUR_AMOUNT_OTHER_C', 'ONE_INSUR_CNT_OTHER_C', 'TWO_INSUR_AMOUNT_OTHER_C', 'TWO_INSUR_CNT_OTHER_C', 'THREE_INSUR_AMOUNT_OTHER_C', 'THREE_INSUR_CNT_OTHER_C', 'FOUR_INSUR_AMOUNT_OTHER_C', 'FOUR_INSUR_CNT_OTHER_C', 'FIVE_INSUR_AMOUNT_OTHER_C', 'FIVE_INSUR_CNT_OTHER_C', 'ONE_PARK_CNT_OTHER_C', 'TWO_PARK_CNT_OTHER_C', 'THREE_PARK_CNT_OTHER_C', 'BUMP_CNT_OTHER_C', 'ONE_INSUR_AMOUNT_COM_C', 'ONE_INSUR_CNT_COM_C', 'TWO_INSUR_AMOUNT_COM_C', 'TWO_INSUR_CNT_COM_C', 'THREE_INSUR_AMOUNT_COM_C', 'THREE_INSUR_CNT_COM_C', 'FOUR_INSUR_AMOUNT_COM_C', 'FOUR_INSUR_CNT_COM_C', 'FIVE_INSUR_AMOUNT_COM_C', 'FIVE_INSUR_CNT_COM_C', 'ONE_PARK_CNT_COM_C', 'TWO_PARK_CNT_COM_C', 'THREE_PARK_CNT_COM_C', 'BUMP_CNT_COM_C', 'DRIVER_CONCLUDE_AMOUNT_1Y', 'DRIVER_TIMES_1Y', 'DRIVER_CONCLUDE_AMOUNT_2Y', 'DRIVER_TIMES_2Y', 'DRIVER_CONCLUDE_AMOUNT_3Y', 'DRIVER_TIMES_3Y', 'INSURE')
integer_col=c(integer_col1,integer_col2)
# integer_col = c('DISCOUNT_PREMIUM',	'INS_ISSUE_YEAR',	'CAR_AGE',	'INS_AGE',	'APC_AGE',	'ONE_INSUR_AMOUNT',	'ONE_INSUR_CNT',	'TWO_INSUR_AMOUNT',	'TWO_INSUR_CNT',	'THREE_INSUR_AMOUNT',	'THREE_INSUR_CNT',	'FOUR_INSUR_AMOUNT',	'FOUR_INSUR_CNT',	'FIVE_INSUR_AMOUNT',	'FIVE_INSUR_CNT',	'ONE_PARK_CNT',	'TWO_PARK_CNT',	'THREE_PARK_CNT',	'BUMP_CNT',	'ONE_INSUR_AMOUNT_BODY',	'ONE_INSUR_CNT_BODY',	'TWO_INSUR_AMOUNT_BODY',	'TWO_INSUR_CNT_BODY',	'THREE_INSUR_AMOUNT_BODY',	'THREE_INSUR_CNT_BODY',	'FOUR_INSUR_AMOUNT_BODY',	'FOUR_INSUR_CNT_BODY',	'FIVE_INSUR_AMOUNT_BODY',	'FIVE_INSUR_CNT_BODY',	'ONE_PARK_CNT_BODY',	'TWO_PARK_CNT_BODY',	'THREE_PARK_CNT_BODY',	'BUMP_CNT_BODY',	'ONE_INSUR_AMOUNT_BURG',	'ONE_INSUR_CNT_BURG',	'TWO_INSUR_AMOUNT_BURG',	'TWO_INSUR_CNT_BURG',	'THREE_INSUR_AMOUNT_BURG',	'THREE_INSUR_CNT_BURG',	'FOUR_INSUR_AMOUNT_BURG',	'FOUR_INSUR_CNT_BURG',	'FIVE_INSUR_AMOUNT_BURG',	'FIVE_INSUR_CNT_BURG',	'ONE_PARK_CNT_BURG',	'TWO_PARK_CNT_BURG',	'THREE_PARK_CNT_BURG',	'BUMP_CNT_BURG',	'ONE_INSUR_AMOUNT_THIRD',	'ONE_INSUR_CNT_THIRD',	'TWO_INSUR_AMOUNT_THIRD',	'TWO_INSUR_CNT_THIRD',	'THREE_INSUR_AMOUNT_THIRD',	'THREE_INSUR_CNT_THIRD',	'FOUR_INSUR_AMOUNT_THIRD',	'FOUR_INSUR_CNT_THIRD',	'FIVE_INSUR_AMOUNT_THIRD',	'FIVE_INSUR_CNT_THIRD',	'ONE_PARK_CNT_THIRD',	'TWO_PARK_CNT_THIRD',	'THREE_PARK_CNT_THIRD',	'BUMP_CNT_THIRD',	'ONE_INSUR_AMOUNT_CUST',	'ONE_INSUR_CNT_CUST',	'TWO_INSUR_AMOUNT_CUST',	'TWO_INSUR_CNT_CUST',	'THREE_INSUR_AMOUNT_CUST',	'THREE_INSUR_CNT_CUST',	'FOUR_INSUR_AMOUNT_CUST',	'FOUR_INSUR_CNT_CUST',	'FIVE_INSUR_AMOUNT_CUST',	'FIVE_INSUR_CNT_CUST',	'ONE_PARK_CNT_CUST',	'TWO_PARK_CNT_CUST',	'THREE_PARK_CNT_CUST',	'BUMP_CNT_CUST',	'ONE_INSUR_AMOUNT_FORCE',	'ONE_INSUR_CNT_FORCE',	'TWO_INSUR_AMOUNT_FORCE',	'TWO_INSUR_CNT_FORCE',	'THREE_INSUR_AMOUNT_FORCE',	'THREE_INSUR_CNT_FORCE',	'FOUR_INSUR_AMOUNT_FORCE',	'FOUR_INSUR_CNT_FORCE',	'FIVE_INSUR_AMOUNT_FORCE',	'FIVE_INSUR_CNT_FORCE',	'ONE_PARK_CNT_FORCE',	'TWO_PARK_CNT_FORCE',	'THREE_PARK_CNT_FORCE',	'BUMP_CNT_FORCE',	'ONE_INSUR_AMOUNT_OTHER',	'ONE_INSUR_CNT_OTHER',	'TWO_INSUR_AMOUNT_OTHER',	'TWO_INSUR_CNT_OTHER',	'THREE_INSUR_AMOUNT_OTHER',	'THREE_INSUR_CNT_OTHER',	'FOUR_INSUR_AMOUNT_OTHER',	'FOUR_INSUR_CNT_OTHER',	'FIVE_INSUR_AMOUNT_OTHER',	'FIVE_INSUR_CNT_OTHER',	'ONE_PARK_CNT_OTHER',	'TWO_PARK_CNT_OTHER',	'THREE_PARK_CNT_OTHER',	'BUMP_CNT_OTHER',	'ONE_INSUR_AMOUNT_COM',	'ONE_INSUR_CNT_COM',	'TWO_INSUR_AMOUNT_COM',	'TWO_INSUR_CNT_COM',	'THREE_INSUR_AMOUNT_COM',	'THREE_INSUR_CNT_COM',	'FOUR_INSUR_AMOUNT_COM',	'FOUR_INSUR_CNT_COM',	'FIVE_INSUR_AMOUNT_COM',	'FIVE_INSUR_CNT_COM',	'ONE_PARK_CNT_COM',	'TWO_PARK_CNT_COM',	'THREE_PARK_CNT_COM',	'BUMP_CNT_COM',	'ONE_INSUR_AMOUNT_C',	'ONE_INSUR_CNT_C',	'TWO_INSUR_AMOUNT_C',	'TWO_INSUR_CNT_C',	'THREE_INSUR_AMOUNT_C',	'THREE_INSUR_CNT_C',	'FOUR_INSUR_AMOUNT_C',	'FOUR_INSUR_CNT_C',	'FIVE_INSUR_AMOUNT_C',	'FIVE_INSUR_CNT_C',	'ONE_PARK_CNT_C',	'TWO_PARK_CNT_C',	'THREE_PARK_CNT_C',	'IS_BUMP_C',	'BUMP_CNT_C',	'ONE_INSUR_AMOUNT_BODY_C',	'ONE_INSUR_CNT_BODY_C',	'TWO_INSUR_AMOUNT_BODY_C',	'TWO_INSUR_CNT_BODY_C',	'THREE_INSUR_AMOUNT_BODY_C',	'THREE_INSUR_CNT_BODY_C',	'FOUR_INSUR_AMOUNT_BODY_C',	'FOUR_INSUR_CNT_BODY_C',	'FIVE_INSUR_AMOUNT_BODY_C',	'FIVE_INSUR_CNT_BODY_C',	'ONE_PARK_CNT_BODY_C',	'TWO_PARK_CNT_BODY_C',	'THREE_PARK_CNT_BODY_C',	'BUMP_CNT_BODY_C',	'ONE_INSUR_AMOUNT_BURG_C',	'ONE_INSUR_CNT_BURG_C',	'TWO_INSUR_AMOUNT_BURG_C',	'TWO_INSUR_CNT_BURG_C',	'THREE_INSUR_AMOUNT_BURG_C',	'THREE_INSUR_CNT_BURG_C',	'FOUR_INSUR_AMOUNT_BURG_C',	'FOUR_INSUR_CNT_BURG_C',	'FIVE_INSUR_AMOUNT_BURG_C',	'FIVE_INSUR_CNT_BURG_C',	'ONE_PARK_CNT_BURG_C',	'TWO_PARK_CNT_BURG_C',	'THREE_PARK_CNT_BURG_C',	'BUMP_CNT_BURG_C',	'ONE_INSUR_AMOUNT_THIRD_C',	'ONE_INSUR_CNT_THIRD_C',	'TWO_INSUR_AMOUNT_THIRD_C',	'TWO_INSUR_CNT_THIRD_C',	'THREE_INSUR_AMOUNT_THIRD_C',	'THREE_INSUR_CNT_THIRD_C',	'FOUR_INSUR_AMOUNT_THIRD_C',	'FOUR_INSUR_CNT_THIRD_C',	'FIVE_INSUR_AMOUNT_THIRD_C',	'FIVE_INSUR_CNT_THIRD_C',	'ONE_PARK_CNT_THIRD_C',	'TWO_PARK_CNT_THIRD_C',	'THREE_PARK_CNT_THIRD_C',	'BUMP_CNT_THIRD_C',	'ONE_INSUR_AMOUNT_CUST_C',	'ONE_INSUR_CNT_CUST_C',	'TWO_INSUR_AMOUNT_CUST_C',	'TWO_INSUR_CNT_CUST_C',	'THREE_INSUR_AMOUNT_CUST_C',	'THREE_INSUR_CNT_CUST_C',	'FOUR_INSUR_AMOUNT_CUST_C',	'FOUR_INSUR_CNT_CUST_C',	'FIVE_INSUR_AMOUNT_CUST_C',	'FIVE_INSUR_CNT_CUST_C',	'ONE_PARK_CNT_CUST_C',	'TWO_PARK_CNT_CUST_C',	'THREE_PARK_CNT_CUST_C',	'BUMP_CNT_CUST_C',	'ONE_INSUR_AMOUNT_FORCE_C',	'ONE_INSUR_CNT_FORCE_C',	'TWO_INSUR_AMOUNT_FORCE_C',	'TWO_INSUR_CNT_FORCE_C',	'THREE_INSUR_AMOUNT_FORCE_C',	'THREE_INSUR_CNT_FORCE_C',	'FOUR_INSUR_AMOUNT_FORCE_C',	'FOUR_INSUR_CNT_FORCE_C',	'FIVE_INSUR_AMOUNT_FORCE_C',	'FIVE_INSUR_CNT_FORCE_C',	'ONE_PARK_CNT_FORCE_C',	'TWO_PARK_CNT_FORCE_C',	'THREE_PARK_CNT_FORCE_C',	'BUMP_CNT_FORCE_C',	'ONE_INSUR_AMOUNT_OTHER_C',	'ONE_INSUR_CNT_OTHER_C',	'TWO_INSUR_AMOUNT_OTHER_C',	'TWO_INSUR_CNT_OTHER_C',	'THREE_INSUR_AMOUNT_OTHER_C',	'THREE_INSUR_CNT_OTHER_C',	'FOUR_INSUR_AMOUNT_OTHER_C',	'FOUR_INSUR_CNT_OTHER_C',	'FIVE_INSUR_AMOUNT_OTHER_C',	'FIVE_INSUR_CNT_OTHER_C',	'ONE_PARK_CNT_OTHER_C',	'TWO_PARK_CNT_OTHER_C',	'THREE_PARK_CNT_OTHER_C',	'BUMP_CNT_OTHER_C',	'ONE_INSUR_AMOUNT_COM_C',	'ONE_INSUR_CNT_COM_C',	'TWO_INSUR_AMOUNT_COM_C',	'TWO_INSUR_CNT_COM_C',	'THREE_INSUR_AMOUNT_COM_C',	'THREE_INSUR_CNT_COM_C',	'FOUR_INSUR_AMOUNT_COM_C',	'FOUR_INSUR_CNT_COM_C',	'FIVE_INSUR_AMOUNT_COM_C',	'FIVE_INSUR_CNT_COM_C',	'ONE_PARK_CNT_COM_C',	'TWO_PARK_CNT_COM_C',	'THREE_PARK_CNT_COM_C',	'BUMP_CNT_COM_C',	'DRIVER_CONCLUDE_AMOUNT_1Y',	'DRIVER_TIMES_1Y',	'DRIVER_CONCLUDE_AMOUNT_2Y',	'DRIVER_TIMES_2Y',	'DRIVER_CONCLUDE_AMOUNT_3Y',	'DRIVER_TIMES_3Y',	'INSURE')
factor_col = c('IS_CONTINUE_POLICY',	'IS_NEW_POLICY',	'BODY_CLAIM_CODE',	'UNIT_NO',	'IS_FORCE_DEGREE_CH',	'LIMIT_DRIVER',	'IS_ADD_OUTFIT',	'IS_NEW_CAR',	'IS_CHANGE_CARNO',	'IS_TRADE_FORCE',	'VEHICLE_KIND_NO',	'IS_MAIN_INSURED',	'INS_SEX',	'INS_MARRIAGE',	'OCCU_CATCODE_INS',	'IS_SAME',	'APC_RELATION_INS',	'APC_SEX',	'APC_MARRIAGE',	'OCCU_CATCODE_APC',	'INTRDUCE_KIND',	'AGENT_KIND',	'BROKER_NO',	'CATEGORY_CODE',	'CATEGORY_KIND',	'IS_BUMP',	'IS_BUMP_BODY',	'IS_BUMP_BURG',	'IS_BUMP_THIRD',	'IS_BUMP_CUST',	'IS_BUMP_FORCE',	'IS_BUMP_OTHER',	'IS_BUMP_COM',	'IS_BUMP_BODY_C',	'IS_BUMP_BURG_C',	'IS_BUMP_THIRD_C',	'IS_BUMP_CUST_C',	'IS_BUMP_FORCE_C',	'IS_BUMP_OTHER_C',	'IS_BUMP_COM_C',	'BODY_MAIN',	'IS_UNCLEAR',	'IS_WEATHER',	'IS_HUMAN',	'IS_DEPRECIATION',	'IS_RECOVERY',	'INS_ZIP_CODE',	'INS_SCHOOL_DEGREE',	'INS_IS_ONE_YEAR_REPAIR',	'INS_IS_TERR',	'APC_IS_TERR',	'INS_SAN',	'APC_SAN',	'INS_AM',	'APC_AM',	'INS_SIP',	'APC_SIP',	'INS_ML_TF',	'APC_ML_TF',	'INS_IS_INSUR_STRICT',	'APC_IS_INSUR_STRICT',	'INS_IS_REPAIR',	'INS_IS_DRUNK_DRIVING',	'INS_IS_MAIN_CAUSE',	'INS_IS_CLAIM_MANY',	'INS_IS_BAD_CUSTOMER',	'INS_IS_MORALS_RISK',	'INS_IS_FRAUD_GROUP',	'IS_HPRICE_CAR',	'POLICY_RESULT_CODE')
Date_col = c('START_DATETIME')
character_col = c('CONTRACT_NO',	'ENGINE_NO',	'INTRDUCE_DIV_NO',	'COUNSEL_DIV_NO',	'AGENT_DIV_NO') 

dataset = typechange(dataset,numeric_col,integer_col,factor_col,Date_col,character_col)
glimpse(dataset)


# 進行各資料探勘
DM_result = autoDataMining(dataset)
# write.csv(DM_result,'資料探勘結果.csv')

# 進行各個欄位的探勘
# 類別欄位
# col_name='INSRNCE_AMOUNT'
# table(dataset[[col_name]])
# prop.table(table(dataset[[col_name]]))
# plot(dataset[[col_name]])
# 連續欄位
# col_name='INSRNCE_AMOUNT'
# summary(dataset[[col_name]])
# plot(density(dataset[[col_name]]))
# hist(dataset[[col_name]])
# boxplot(dataset[[col_name]])
# 
# summary(log(dataset[[col_name]]))
# boxplot(log(dataset[[col_name]]))
# p = hist(log(dataset[[col_name]]))
# plot(p, freq = FALSE,main="Probability density function of variable")
# x=seq(min(p$breaks),max(p$breaks),by=0.02)
# curve(dnorm(x, mean(log(dataset[[col_name]])), sd(log(dataset[[col_name]]))), add=TRUE)
# 
# summary(log(dataset[[col_name]]+1))
# boxplot(log(dataset[[col_name]]+1))
# p = hist(log(dataset[[col_name]]+1))
# plot(p, freq = FALSE,main="Probability density function of variable")
# x=seq(min(p$breaks),max(p$breaks),by=0.02)
# curve(dnorm(x, mean(log(dataset[[col_name]]+1)), sd(log(dataset[[col_name]]+1))), add=TRUE)

# 排除異常或不要的欄位
remove_col = names(dataset)  %in% c('CONTRACT_NO', 'IS_CONTINUE_POLICY', 'IS_NEW_POLICY', 'IS_CHANGE_CARNO', 'ENGINE_NO', 'IS_MAIN_INSURED', 'OCCU_CATCODE_INS', 'APC_AGE', 'APC_MARRIAGE', 'OCCU_CATCODE_APC', 'INTRDUCE_DIV_NO', 'AGENT_DIV_NO', 'COUNSEL_DIV_NO', 'CATEGORY_KIND', 'ONE_PARK_CNT_BURG', 'TWO_PARK_CNT_BURG', 'THREE_PARK_CNT_BURG', 'ONE_PARK_CNT_CUST', 'TWO_PARK_CNT_CUST', 'THREE_PARK_CNT_CUST', 'ONE_PARK_CNT_COM', 'TWO_PARK_CNT_COM', 'THREE_PARK_CNT_COM', 'ONE_PARK_CNT_BURG_C', 'TWO_PARK_CNT_BURG_C', 'THREE_PARK_CNT_BURG_C', 'ONE_PARK_CNT_CUST_C', 'TWO_PARK_CNT_CUST_C', 'THREE_PARK_CNT_CUST_C', 'ONE_PARK_CNT_COM_C', 'TWO_PARK_CNT_COM_C', 'THREE_PARK_CNT_COM_C', 'INS_ZIP_CODE', 'INS_SCHOOL_DEGREE', 'INS_IS_ONE_YEAR_REPAIR', 'INS_IS_TERR', 'APC_IS_TERR', 'INS_SAN', 'APC_SAN', 'INS_AM', 'APC_AM', 'INS_ML_TF', 'APC_ML_TF', 'INS_IS_DRUNK_DRIVING', 'INSURE')
dataset=dataset[!remove_col] #534361*275

# 資料工程轉換
# 取log
log_col =  names(dataset)  %in% c('DISCOUNT_PREMIUM')
dataset[log_col] = log(dataset[log_col])

# +1取log
plus1_log_col =  names(dataset)  %in% c('INS_ISSUE_YEAR', 'CAR_AGE', 'ONE_INSUR_AMOUNT', 'ONE_INSUR_CNT', 
                                        'TWO_INSUR_AMOUNT', 'TWO_INSUR_CNT', 'THREE_INSUR_AMOUNT', 
                                        'THREE_INSUR_CNT', 'FOUR_INSUR_AMOUNT', 'FOUR_INSUR_CNT', 
                                        'FIVE_INSUR_AMOUNT', 'FIVE_INSUR_CNT', 'ONE_PARK_CNT', 
                                        'TWO_PARK_CNT', 'THREE_PARK_CNT', 'BUMP_CNT', 'ONE_INSUR_AMOUNT_BODY',
                                        'ONE_INSUR_CNT_BODY', 'TWO_INSUR_AMOUNT_BODY', 'TWO_INSUR_CNT_BODY', 
                                        'THREE_INSUR_AMOUNT_BODY', 'THREE_INSUR_CNT_BODY', 
                                        'FOUR_INSUR_AMOUNT_BODY', 'FOUR_INSUR_CNT_BODY', 
                                        'FIVE_INSUR_AMOUNT_BODY', 'FIVE_INSUR_CNT_BODY', 'ONE_PARK_CNT_BODY', 
                                        'TWO_PARK_CNT_BODY', 'THREE_PARK_CNT_BODY', 'BUMP_CNT_BODY', 
                                        'ONE_INSUR_AMOUNT_BURG', 'ONE_INSUR_CNT_BURG', 'TWO_INSUR_AMOUNT_BURG',
                                        'TWO_INSUR_CNT_BURG', 'THREE_INSUR_AMOUNT_BURG', 'THREE_INSUR_CNT_BURG', 
                                        'FOUR_INSUR_AMOUNT_BURG', 'FOUR_INSUR_CNT_BURG', 'FIVE_INSUR_AMOUNT_BURG', 
                                        'FIVE_INSUR_CNT_BURG', 'BUMP_CNT_BURG', 'ONE_INSUR_AMOUNT_THIRD', 
                                        'ONE_INSUR_CNT_THIRD', 'TWO_INSUR_AMOUNT_THIRD', 'TWO_INSUR_CNT_THIRD', 
                                        'THREE_INSUR_AMOUNT_THIRD', 'THREE_INSUR_CNT_THIRD', 'FOUR_INSUR_AMOUNT_THIRD', 
                                        'FOUR_INSUR_CNT_THIRD', 'FIVE_INSUR_AMOUNT_THIRD', 'FIVE_INSUR_CNT_THIRD', 'ONE_PARK_CNT_THIRD', 'TWO_PARK_CNT_THIRD', 'THREE_PARK_CNT_THIRD', 'BUMP_CNT_THIRD', 'ONE_INSUR_AMOUNT_CUST', 'ONE_INSUR_CNT_CUST', 'TWO_INSUR_AMOUNT_CUST', 'TWO_INSUR_CNT_CUST', 'THREE_INSUR_AMOUNT_CUST', 'THREE_INSUR_CNT_CUST', 'FOUR_INSUR_AMOUNT_CUST', 'FOUR_INSUR_CNT_CUST', 'FIVE_INSUR_AMOUNT_CUST', 'FIVE_INSUR_CNT_CUST', 'BUMP_CNT_CUST', 'ONE_INSUR_AMOUNT_FORCE', 'ONE_INSUR_CNT_FORCE', 'TWO_INSUR_AMOUNT_FORCE', 'TWO_INSUR_CNT_FORCE', 'THREE_INSUR_AMOUNT_FORCE', 'THREE_INSUR_CNT_FORCE', 'FOUR_INSUR_AMOUNT_FORCE', 'FOUR_INSUR_CNT_FORCE', 'FIVE_INSUR_AMOUNT_FORCE', 'FIVE_INSUR_CNT_FORCE', 'ONE_PARK_CNT_FORCE', 'TWO_PARK_CNT_FORCE', 'THREE_PARK_CNT_FORCE', 'BUMP_CNT_FORCE', 'ONE_INSUR_AMOUNT_OTHER', 'ONE_INSUR_CNT_OTHER', 'TWO_INSUR_AMOUNT_OTHER', 'TWO_INSUR_CNT_OTHER', 'THREE_INSUR_AMOUNT_OTHER', 'THREE_INSUR_CNT_OTHER', 'FOUR_INSUR_AMOUNT_OTHER', 'FOUR_INSUR_CNT_OTHER', 'FIVE_INSUR_AMOUNT_OTHER', 'FIVE_INSUR_CNT_OTHER', 'ONE_PARK_CNT_OTHER', 'TWO_PARK_CNT_OTHER', 'THREE_PARK_CNT_OTHER', 'BUMP_CNT_OTHER', 'ONE_INSUR_AMOUNT_COM', 'ONE_INSUR_CNT_COM', 'TWO_INSUR_AMOUNT_COM', 'TWO_INSUR_CNT_COM', 'THREE_INSUR_AMOUNT_COM', 'THREE_INSUR_CNT_COM', 'FOUR_INSUR_AMOUNT_COM', 'FOUR_INSUR_CNT_COM', 'FIVE_INSUR_AMOUNT_COM', 'FIVE_INSUR_CNT_COM', 'BUMP_CNT_COM', 
                                        'ONE_INSUR_AMOUNT_C', 'ONE_INSUR_CNT_C', 'TWO_INSUR_AMOUNT_C', 'TWO_INSUR_CNT_C', 'THREE_INSUR_AMOUNT_C', 'THREE_INSUR_CNT_C', 'FOUR_INSUR_AMOUNT_C', 'FOUR_INSUR_CNT_C', 'FIVE_INSUR_AMOUNT_C', 'FIVE_INSUR_CNT_C', 'ONE_PARK_CNT_C', 'TWO_PARK_CNT_C', 'THREE_PARK_CNT_C', 'IS_BUMP_C', 'BUMP_CNT_C', 'ONE_INSUR_AMOUNT_BODY_C', 'ONE_INSUR_CNT_BODY_C', 'TWO_INSUR_AMOUNT_BODY_C', 'TWO_INSUR_CNT_BODY_C', 'THREE_INSUR_AMOUNT_BODY_C', 'THREE_INSUR_CNT_BODY_C', 'FOUR_INSUR_AMOUNT_BODY_C', 'FOUR_INSUR_CNT_BODY_C', 'FIVE_INSUR_AMOUNT_BODY_C', 'FIVE_INSUR_CNT_BODY_C', 'ONE_PARK_CNT_BODY_C', 'TWO_PARK_CNT_BODY_C', 'THREE_PARK_CNT_BODY_C', 'BUMP_CNT_BODY_C', 'ONE_INSUR_AMOUNT_BURG_C', 'ONE_INSUR_CNT_BURG_C', 'TWO_INSUR_AMOUNT_BURG_C', 'TWO_INSUR_CNT_BURG_C', 'THREE_INSUR_AMOUNT_BURG_C', 'THREE_INSUR_CNT_BURG_C', 'FOUR_INSUR_AMOUNT_BURG_C', 'FOUR_INSUR_CNT_BURG_C', 'FIVE_INSUR_AMOUNT_BURG_C', 'FIVE_INSUR_CNT_BURG_C', 'BUMP_CNT_BURG_C', 'ONE_INSUR_AMOUNT_THIRD_C', 'ONE_INSUR_CNT_THIRD_C', 'TWO_INSUR_AMOUNT_THIRD_C', 'TWO_INSUR_CNT_THIRD_C', 'THREE_INSUR_AMOUNT_THIRD_C', 'THREE_INSUR_CNT_THIRD_C', 'FOUR_INSUR_AMOUNT_THIRD_C', 'FOUR_INSUR_CNT_THIRD_C', 'FIVE_INSUR_AMOUNT_THIRD_C', 'FIVE_INSUR_CNT_THIRD_C', 'ONE_PARK_CNT_THIRD_C', 'TWO_PARK_CNT_THIRD_C', 'THREE_PARK_CNT_THIRD_C', 'BUMP_CNT_THIRD_C', 'ONE_INSUR_AMOUNT_CUST_C', 'ONE_INSUR_CNT_CUST_C', 'TWO_INSUR_AMOUNT_CUST_C', 'TWO_INSUR_CNT_CUST_C', 'THREE_INSUR_AMOUNT_CUST_C', 'THREE_INSUR_CNT_CUST_C', 'FOUR_INSUR_AMOUNT_CUST_C', 'FOUR_INSUR_CNT_CUST_C', 'FIVE_INSUR_AMOUNT_CUST_C', 'FIVE_INSUR_CNT_CUST_C', 
                                        'BUMP_CNT_CUST_C', 'ONE_INSUR_AMOUNT_FORCE_C', 'ONE_INSUR_CNT_FORCE_C', 'TWO_INSUR_AMOUNT_FORCE_C', 'TWO_INSUR_CNT_FORCE_C', 'THREE_INSUR_AMOUNT_FORCE_C', 'THREE_INSUR_CNT_FORCE_C', 'FOUR_INSUR_AMOUNT_FORCE_C', 'FOUR_INSUR_CNT_FORCE_C', 'FIVE_INSUR_AMOUNT_FORCE_C', 'FIVE_INSUR_CNT_FORCE_C', 'ONE_PARK_CNT_FORCE_C', 'TWO_PARK_CNT_FORCE_C', 'THREE_PARK_CNT_FORCE_C', 'BUMP_CNT_FORCE_C', 'ONE_INSUR_AMOUNT_OTHER_C', 'ONE_INSUR_CNT_OTHER_C', 'TWO_INSUR_AMOUNT_OTHER_C', 'TWO_INSUR_CNT_OTHER_C', 'THREE_INSUR_AMOUNT_OTHER_C', 'THREE_INSUR_CNT_OTHER_C', 'FOUR_INSUR_AMOUNT_OTHER_C', 'FOUR_INSUR_CNT_OTHER_C', 'FIVE_INSUR_AMOUNT_OTHER_C', 'FIVE_INSUR_CNT_OTHER_C', 'ONE_PARK_CNT_OTHER_C', 'TWO_PARK_CNT_OTHER_C', 'THREE_PARK_CNT_OTHER_C', 'BUMP_CNT_OTHER_C', 'ONE_INSUR_AMOUNT_COM_C', 'ONE_INSUR_CNT_COM_C', 'TWO_INSUR_AMOUNT_COM_C', 'TWO_INSUR_CNT_COM_C', 'THREE_INSUR_AMOUNT_COM_C', 'THREE_INSUR_CNT_COM_C', 'FOUR_INSUR_AMOUNT_COM_C', 'FOUR_INSUR_CNT_COM_C', 'FIVE_INSUR_AMOUNT_COM_C', 'FIVE_INSUR_CNT_COM_C', 'BUMP_CNT_COM_C', 'DRIVER_CONCLUDE_AMOUNT_1Y', 'DRIVER_TIMES_1Y', 'DRIVER_CONCLUDE_AMOUNT_2Y', 'DRIVER_TIMES_2Y', 'DRIVER_CONCLUDE_AMOUNT_3Y', 'DRIVER_TIMES_3Y', 'DISCOUNT_PREMIUM_AGN', 'CONCLUDE_NTD_AMOUNT_AGN', 'POLICY_COUNT_AGN', 'LOSS_RATE_AGN', 'INSRNCE_AMOUNT')
dataset[plus1_log_col] = log(dataset[plus1_log_col]+1)

# 目標變數轉1/0
dataset[,'LOSS_RATE']=as.factor(ifelse(dataset[,'LOSS_RATE'] == 0 , '0', '1')) #534361*275

# 缺失值處理
# 排除缺失法
dataset = dataset[!is.na(dataset[,'INS_MARRIAGE']),] #534319*275

# 特定值補值
dataset['IS_ADD_OUTFIT'][is.na(dataset[,'IS_ADD_OUTFIT']),] = '0'

# 補缺失特定欄位
levels(dataset[['APC_RELATION_INS']])=c(levels(dataset[['APC_RELATION_INS']]), "MIS")
dataset['APC_RELATION_INS'][is.na(dataset[,'APC_RELATION_INS']),] = 'MIS'

levels(dataset[['APC_SEX']])=c(levels(dataset[['APC_SEX']]), "MIS")
dataset['APC_SEX'][is.na(dataset[,'APC_SEX']),] = 'MIS'

# 初步資料處理完成
# 534319*275
# 觀察目標變數
prop.table(table(dataset$LOSS_RATE))

train_pool = dataset[intersect(which(dataset[,'START_DATETIME']>='2012-01-01'),which(dataset[,'START_DATETIME']<'2017-01-01')),]
test_pool = dataset[intersect(which(dataset[,'START_DATETIME']>='2016-01-01'),which(dataset[,'START_DATETIME']<'2018-01-01')),]

# 排除日期欄位
train_pool=train_pool[,-which(colnames(train_pool) %in% 'START_DATETIME')]
test_pool=test_pool[,-which(colnames(test_pool) %in% 'START_DATETIME')]

# H=subset(train_pool,train_pool$LOSS_RATE=='1')
# L=subset(train_pool,train_pool$LOSS_RATE=='0')


################################################################################
################################################################################
################################################################################
# XGB 不平衡樣本
library('doParallel')
cl<-makeCluster(4) #本機建議不要超過4，自行根據硬體設備設定
registerDoParallel(cl)

dummies = dummyVars(LOSS_RATE~., data = train_pool)
TrainData_dmy = predict(dummies, train_pool) # 建立訓練資料的虛擬變量
TestData_dmy = predict(dummies, test_pool) # 建立訓練資料的虛擬變量

Y = train_pool$LOSS_RATE
Y = as.integer(train_pool$LOSS_RATE)-1
Y_test = test_pool$LOSS_RATE

param = list("objective" = "multi:softprob",
             "eval_metric" = "mlogloss",
             "num_class" = 2,
             eta=0.3,
             gamma=0.1
)

xgb = xgboost(param=param, data=TrainData_dmy, label=Y, nrounds=100)

Ypred_LH = predict(xgb,TrainData_dmy)
Ypred_LH = t(matrix(Ypred_LH,2,length(Ypred_LH)/2))
Ypred_LH = levels(train_pool$LOSS_RATE)[max.col(Ypred_LH)]
t0 = table(train_pool$LOSS_RATE,Ypred_LH,dnn = c("實際", "預測"))
t0
TRAIN_ACC <- sum(diag(t0)) / sum(t0)
TRAIN_ACC

Ypred_LH = predict(xgb,TestData_dmy)
Ypred_LH = t(matrix(Ypred_LH,2,length(Ypred_LH)/2))
Ypred_LH = levels(test_pool$LOSS_RATE)[max.col(Ypred_LH)]
t0 = table(test_pool$LOSS_RATE,Ypred_LH,dnn = c("實際", "預測"))
t0
TRAIN_ACC <- sum(diag(t0)) / sum(t0)
TRAIN_ACC

library('MLmetrics')
report_metrics('xgb',test_pool$LOSS_RATE,Ypred_LH)



