rm(list = ls())
gc()
# .rs.restartR()
library(readr)
library(cathayR)
inicathayR()
library('doParallel')
library(caret)
library(xgboost)
cl<-makeCluster(3) #建議不要超過4，自行根據硬體設備設定
registerDoParallel(cl)

train_data = read_csv('train_data.csv')
test_data = read_csv('test_data.csv')

train_data = as.data.frame(train_data)
test_data = as.data.frame(test_data)


col_list1 = c('DISCOUNT_PREMIUM',	'INS_ISSUE_YEAR',	'CAR_AGE',	'INS_AGE',	'ONE_INSUR_AMOUNT',	'ONE_INSUR_CNT',	'TWO_INSUR_AMOUNT',	'TWO_INSUR_CNT',	'THREE_INSUR_AMOUNT',	'THREE_INSUR_CNT',	'FOUR_INSUR_AMOUNT',	'FOUR_INSUR_CNT',	'FIVE_INSUR_AMOUNT',	'FIVE_INSUR_CNT',	'ONE_PARK_CNT',	'TWO_PARK_CNT',	'THREE_PARK_CNT',	'BUMP_CNT',	'ONE_INSUR_AMOUNT_BODY',	'ONE_INSUR_CNT_BODY',	'TWO_INSUR_AMOUNT_BODY',	'TWO_INSUR_CNT_BODY',	'THREE_INSUR_AMOUNT_BODY',	'THREE_INSUR_CNT_BODY',	'FOUR_INSUR_AMOUNT_BODY',	'FOUR_INSUR_CNT_BODY',	'FIVE_INSUR_AMOUNT_BODY',	'FIVE_INSUR_CNT_BODY',	'ONE_PARK_CNT_BODY',	'TWO_PARK_CNT_BODY',	'THREE_PARK_CNT_BODY',	'BUMP_CNT_BODY',	'ONE_INSUR_AMOUNT_BURG',	'ONE_INSUR_CNT_BURG',	'TWO_INSUR_AMOUNT_BURG',	'TWO_INSUR_CNT_BURG',	'THREE_INSUR_AMOUNT_BURG',	'THREE_INSUR_CNT_BURG',	'FOUR_INSUR_AMOUNT_BURG',	'FOUR_INSUR_CNT_BURG',	'FIVE_INSUR_AMOUNT_BURG',	'FIVE_INSUR_CNT_BURG',	'BUMP_CNT_BURG',	'ONE_INSUR_AMOUNT_THIRD',	'ONE_INSUR_CNT_THIRD',	'TWO_INSUR_AMOUNT_THIRD',	'TWO_INSUR_CNT_THIRD',	'THREE_INSUR_AMOUNT_THIRD',	'THREE_INSUR_CNT_THIRD',	'FOUR_INSUR_AMOUNT_THIRD',	'FOUR_INSUR_CNT_THIRD',	'FIVE_INSUR_AMOUNT_THIRD',	'FIVE_INSUR_CNT_THIRD',	'ONE_PARK_CNT_THIRD',	'TWO_PARK_CNT_THIRD',	'THREE_PARK_CNT_THIRD',	'BUMP_CNT_THIRD',	'ONE_INSUR_AMOUNT_CUST',	'ONE_INSUR_CNT_CUST',	'TWO_INSUR_AMOUNT_CUST',	'TWO_INSUR_CNT_CUST',	'THREE_INSUR_AMOUNT_CUST',	'THREE_INSUR_CNT_CUST',	'FOUR_INSUR_AMOUNT_CUST',	'FOUR_INSUR_CNT_CUST',	'FIVE_INSUR_AMOUNT_CUST',	'FIVE_INSUR_CNT_CUST',	'ONE_PARK_CNT_CUST',	'TWO_PARK_CNT_CUST',	'THREE_PARK_CNT_CUST',	'BUMP_CNT_CUST',	'ONE_INSUR_AMOUNT_FORCE',	'ONE_INSUR_CNT_FORCE',	'TWO_INSUR_AMOUNT_FORCE',	'TWO_INSUR_CNT_FORCE',	'THREE_INSUR_AMOUNT_FORCE',	'THREE_INSUR_CNT_FORCE',	'FOUR_INSUR_AMOUNT_FORCE',	'FOUR_INSUR_CNT_FORCE',	'FIVE_INSUR_AMOUNT_FORCE',	'FIVE_INSUR_CNT_FORCE',	'ONE_PARK_CNT_FORCE',	'TWO_PARK_CNT_FORCE',	'THREE_PARK_CNT_FORCE',	'BUMP_CNT_FORCE',	'ONE_INSUR_AMOUNT_OTHER',	'ONE_INSUR_CNT_OTHER',	'TWO_INSUR_AMOUNT_OTHER',	'TWO_INSUR_CNT_OTHER',	'THREE_INSUR_AMOUNT_OTHER',	'THREE_INSUR_CNT_OTHER',	'FOUR_INSUR_AMOUNT_OTHER',	'FOUR_INSUR_CNT_OTHER',	'FIVE_INSUR_AMOUNT_OTHER',	'FIVE_INSUR_CNT_OTHER',	'ONE_PARK_CNT_OTHER',	'TWO_PARK_CNT_OTHER',	'THREE_PARK_CNT_OTHER',	'BUMP_CNT_OTHER',	'ONE_INSUR_AMOUNT_COM',	'ONE_INSUR_CNT_COM',	'TWO_INSUR_AMOUNT_COM',	'TWO_INSUR_CNT_COM',	'THREE_INSUR_AMOUNT_COM',	'THREE_INSUR_CNT_COM',	'FOUR_INSUR_AMOUNT_COM',	'FOUR_INSUR_CNT_COM',	'FIVE_INSUR_AMOUNT_COM',	'FIVE_INSUR_CNT_COM',	'BUMP_CNT_COM',	'ONE_INSUR_CNT_C',	'TWO_INSUR_AMOUNT_C',	'TWO_INSUR_CNT_C',	'THREE_INSUR_AMOUNT_C')
col_list2 = c('THREE_INSUR_CNT_C',	'FOUR_INSUR_AMOUNT_C',	'FOUR_INSUR_CNT_C',	'FIVE_INSUR_AMOUNT_C',	'FIVE_INSUR_CNT_C',	'ONE_PARK_CNT_C',	'TWO_PARK_CNT_C',	'THREE_PARK_CNT_C',	'BUMP_CNT_C',	'ONE_INSUR_AMOUNT_BODY_C',	'ONE_INSUR_CNT_BODY_C',	'TWO_INSUR_AMOUNT_BODY_C',	'TWO_INSUR_CNT_BODY_C',	'THREE_INSUR_AMOUNT_BODY_C',	'THREE_INSUR_CNT_BODY_C',	'FOUR_INSUR_AMOUNT_BODY_C',	'FOUR_INSUR_CNT_BODY_C',	'FIVE_INSUR_AMOUNT_BODY_C',	'FIVE_INSUR_CNT_BODY_C',	'ONE_PARK_CNT_BODY_C',	'TWO_PARK_CNT_BODY_C',	'THREE_PARK_CNT_BODY_C',	'BUMP_CNT_BODY_C',	'ONE_INSUR_AMOUNT_BURG_C',	'ONE_INSUR_CNT_BURG_C',	'TWO_INSUR_AMOUNT_BURG_C',	'TWO_INSUR_CNT_BURG_C',	'THREE_INSUR_AMOUNT_BURG_C',	'THREE_INSUR_CNT_BURG_C',	'FOUR_INSUR_AMOUNT_BURG_C',	'FOUR_INSUR_CNT_BURG_C',	'FIVE_INSUR_AMOUNT_BURG_C',	'FIVE_INSUR_CNT_BURG_C',	'BUMP_CNT_BURG_C',	'ONE_INSUR_AMOUNT_THIRD_C',	'ONE_INSUR_CNT_THIRD_C',	'TWO_INSUR_AMOUNT_THIRD_C',	'TWO_INSUR_CNT_THIRD_C',	'THREE_INSUR_AMOUNT_THIRD_C',	'THREE_INSUR_CNT_THIRD_C',	'FOUR_INSUR_AMOUNT_THIRD_C',	'FOUR_INSUR_CNT_THIRD_C',	'FIVE_INSUR_AMOUNT_THIRD_C',	'FIVE_INSUR_CNT_THIRD_C',	'ONE_PARK_CNT_THIRD_C',	'TWO_PARK_CNT_THIRD_C',	'THREE_PARK_CNT_THIRD_C',	'BUMP_CNT_THIRD_C',	'ONE_INSUR_AMOUNT_CUST_C',	'ONE_INSUR_CNT_CUST_C',	'TWO_INSUR_AMOUNT_CUST_C',	'TWO_INSUR_CNT_CUST_C',	'THREE_INSUR_AMOUNT_CUST_C',	'THREE_INSUR_CNT_CUST_C',	'FOUR_INSUR_AMOUNT_CUST_C',	'FOUR_INSUR_CNT_CUST_C',	'FIVE_INSUR_AMOUNT_CUST_C',	'FIVE_INSUR_CNT_CUST_C',	'ONE_PARK_CNT_CUST_C',	'TWO_PARK_CNT_CUST_C',	'THREE_PARK_CNT_CUST_C',	'BUMP_CNT_CUST_C',	'ONE_INSUR_AMOUNT_FORCE_C',	'ONE_INSUR_CNT_FORCE_C',	'TWO_INSUR_AMOUNT_FORCE_C',	'TWO_INSUR_CNT_FORCE_C',	'THREE_INSUR_AMOUNT_FORCE_C',	'THREE_INSUR_CNT_FORCE_C',	'FOUR_INSUR_AMOUNT_FORCE_C',	'FOUR_INSUR_CNT_FORCE_C',	'FIVE_INSUR_AMOUNT_FORCE_C',	'FIVE_INSUR_CNT_FORCE_C',	'ONE_PARK_CNT_FORCE_C',	'TWO_PARK_CNT_FORCE_C',	'THREE_PARK_CNT_FORCE_C',	'BUMP_CNT_FORCE_C',	'ONE_INSUR_AMOUNT_OTHER_C',	'ONE_INSUR_CNT_OTHER_C',	'TWO_INSUR_AMOUNT_OTHER_C',	'TWO_INSUR_CNT_OTHER_C',	'THREE_INSUR_AMOUNT_OTHER_C',	'THREE_INSUR_CNT_OTHER_C',	'FOUR_INSUR_AMOUNT_OTHER_C',	'FOUR_INSUR_CNT_OTHER_C',	'FIVE_INSUR_AMOUNT_OTHER_C',	'FIVE_INSUR_CNT_OTHER_C',	'ONE_PARK_CNT_OTHER_C',	'TWO_PARK_CNT_OTHER_C',	'THREE_PARK_CNT_OTHER_C',	'BUMP_CNT_OTHER_C',	'ONE_INSUR_AMOUNT_COM_C',	'ONE_INSUR_CNT_COM_C',	'TWO_INSUR_AMOUNT_COM_C',	'TWO_INSUR_CNT_COM_C',	'THREE_INSUR_AMOUNT_COM_C',	'THREE_INSUR_CNT_COM_C',	'FOUR_INSUR_AMOUNT_COM_C',	'FOUR_INSUR_CNT_COM_C',	'FIVE_INSUR_AMOUNT_COM_C',	'FIVE_INSUR_CNT_COM_C',	'BUMP_CNT_COM_C',	'DRIVER_CONCLUDE_AMOUNT_1Y',	'DRIVER_TIMES_1Y',	'DRIVER_CONCLUDE_AMOUNT_2Y',	'DRIVER_TIMES_2Y',	'DRIVER_CONCLUDE_AMOUNT_3Y',	'DRIVER_TIMES_3Y',	'DISCOUNT_PREMIUM_AGN',	'CONCLUDE_NTD_AMOUNT_AGN',	'LOSS_RATE_AGN',	'INSRNCE_AMOUNT')
train_pca = train_data[,c(col_list1,col_list2)]

# PCA
pca <- prcomp(formula = ~ .,
              data = train_pca)                          # 正規化資料

plot(pca,         # 放pca
     type="line") # 主標題
# 用藍線標示出特徵值=1的地方
abline(h=1, col="blue") # Kaiser eigenvalue-greater-than-one rule
# pca$rotation 
top3_pca.data <- pca$x[, 1:3]
top3_pca.data = as.data.frame(top3_pca.data)
top3_pca.data[1,]

pca$

